# Chapter 2. Generating Datasets From Selected Variables

To make things easier, 13 variables have been selected from the acs database. Following are the 15 variables with their corresponding names:

1. **Over 65 years old population (age)**
2. **Education Attainment (education):**
    * Below 9th grade
    * Some highschool
    * Some college
    * Advanced Degree
3. **Civil Employment (employment):**
    * Employed
    * Unemployed
4. **Ethnicity (ethnicity):**
    * Hispanic or Latino
    * Not Hispanic or Latino
5. **Rent to Income Ratio (rent_to_income):**
    * Less than 30 percent
    * Greater than 30 percent
6. **Housing tenure (tenure):**
    * Renter occupied
    * Owner occupied
7. **Housing  Vacancy (vacancy):**
    * Sold, not occupied
    * For seasonal, recreational, or occuational use
    * For sale only
    * Rented, not occupied
    * For rent
    * Other vacant
    * For migrant workers
8. **Years houses built (years):**
    * Built 1940 to 1949
    * ...
    * Built 2014 or later
9.  **Median Income (income):**
    * median income white
    * median income black
    * median income hispanic
    * median income total
10. **Median Income to Poverty Level Income (poverty):**
    * >2x_poverty: estimate of people whose income is greater than twice of the poverty level income
    * >poverty: estimate of people whose income is between the poverty level and the twice of the poverty level
    * <poverty: estimate of people earning less than the poverty level
11. **Insurance Coverage (insurance):**
    * With health insurance coverage
    * No health insurance coverage
12. **Nativity (nativitiy):**
    * Native
    * Foreign-Born
13. **Number of Vehicles (means):**
    * No vehicle
    * >1 vehicle : at least one vehicle
14. **Commuting Time (travel):**
    * Less than 5 minutes
    * ...
    * 90 or more minutes

## **Tract Level Datasets**

In [1]:
import gen_datasets

To generate tract level datasets from the census website, you have two functions:
- **tract_level_raw()** : gives you raw estimates for the topic you choose
- **tract_level_perc()** : gives you percentage estimates for the topic you choose

**_Note that gen_datasets is interactive in that it asks you to enter additional information after you run the function_**

### **Function 1 : tract_level_raw()**

In [2]:
gen_datasets.tract_level_raw()

['age', 'education', 'employment', 'ethnicity', 'rent_to_income', 'tenure', 'vacancy', 'years', 'income', 'poverty', 'insurance', 'nativity', 'means', 'travel']

type a variable to look up from above :  insurance

,FIPS,Tract,County,State,With health insurance coverage,No health insurance coverage,total
0,21005950201,Census Tract 9502.01,Anderson County,Kentucky,7622.0,3072.0,5094.0
1,21005950202,Census Tract 9502.02,Anderson County,Kentucky,6008.0,2386.0,3858.0
2,21013961100,Census Tract 9611,Bell County,Kentucky,4202.0,1771.0,2793.0
3,21015070311,Census Tract 703.11,Boone County,Kentucky,4146.0,1834.0,2676.0
4,21015070312,Census Tract 703.12,Boone County,Kentucky,5047.0,2222.0,3254.0
...,...,...,...,...,...,...,...
1110,21095970200,Census Tract 9702,Harlan County,Kentucky,4498.0,1898.0,2881.0
1111,21095970900,Census Tract 9709,Harlan County,Kentucky,5778.0,2533.0,3667.0
1112,21095970100,Census Tract 9701,Harlan County,Kentucky,2221.0,872.0,1446.0
1113,21095970700,Census Tract 9707,Harlan County,Kentucky,5977.0,2421.0,3743.0
1114,21095970800,Census Tract 9708,Harlan County,Kentucky,1734.0,626.0,1077.0

### **Function 2 : tract_level_prec()**

In [3]:
gen_datasets.tract_level_perc()

['age', 'education', 'employment', 'ethnicity', 'rent_to_income', 'tenure', 'vacancy', 'years', 'income', 'poverty', 'insurance', 'nativity', 'means', 'travel']

type a variable to look up from above :  poverty

,FIPS,Tract,County,State,>2x_poverty,>poverty,<poverty
0,21005950201,Census Tract 9502.01,Anderson County,Kentucky,0.622439,0.152377,0.225184
1,21005950202,Census Tract 9502.02,Anderson County,Kentucky,0.691809,0.175220,0.132970
2,21013961100,Census Tract 9611,Bell County,Kentucky,0.361725,0.304096,0.334179
3,21015070311,Census Tract 703.11,Boone County,Kentucky,0.608240,0.206742,0.185019
4,21015070312,Census Tract 703.12,Boone County,Kentucky,0.822631,0.112531,0.064838
...,...,...,...,...,...,...,...
1110,21095970200,Census Tract 9702,Harlan County,Kentucky,0.437345,0.204118,0.358537
1111,21095970900,Census Tract 9709,Harlan County,Kentucky,0.388357,0.190216,0.421427
1112,21095970100,Census Tract 9701,Harlan County,Kentucky,0.530513,0.244105,0.225381
1113,21095970700,Census Tract 9707,Harlan County,Kentucky,0.381754,0.276677,0.341569
1114,21095970800,Census Tract 9708,Harlan County,Kentucky,0.536585,0.227317,0.236098

## **County Level Datasets**

Similar to the tract level datasets, in order to generate tract level datasets from the census website, you have two functions:
- **county_level_raw()** : gives you raw estimates for the topic you choose
- **county_level_perc()** : gives you percentage estimates for the topic you choose

### **Function 3 : county_level_raw()**

In [4]:
gen_datasets.county_level_raw()

['age', 'education', 'employment', 'ethnicity', 'rent_to_income', 'tenure', 'vacancy', 'years', 'income', 'poverty', 'insurance', 'nativity', 'means', 'travel']

type a variable to look up from above :  income

,index,State,County,median_income_white,median_income_black,median_income_hisp,median_income_total
0,0,Kentucky,Adair County,277061.0,45426.0,NaN,268149.0
1,1,Kentucky,Allen County,271754.0,NaN,NaN,273221.0
2,2,Kentucky,Anderson County,298913.0,42000.0,NaN,291718.0
3,3,Kentucky,Ballard County,138163.0,NaN,NaN,135978.0
4,4,Kentucky,Barren County,430626.0,112353.0,39013.0,433498.0
...,...,...,...,...,...,...,...
115,115,Kentucky,Wayne County,176632.0,NaN,NaN,176373.0
116,116,Kentucky,Webster County,170985.0,NaN,35142.0,166632.0
117,117,Kentucky,Whitley County,304734.0,NaN,NaN,303153.0
118,118,Kentucky,Wolfe County,52198.0,NaN,NaN,52048.0
119,119,Kentucky,Woodford County,540365.0,83876.0,129902.0,523925.0

### **Function 4 : county_level_perc()**

In [5]:
gen_datasets.county_level_perc()

['age', 'education', 'employment', 'ethnicity', 'rent_to_income', 'tenure', 'vacancy', 'years', 'income', 'poverty', 'insurance', 'nativity', 'means', 'travel']

type a variable to look up from above :  insurance

,State,County,With health insurance coverage,No health insurance coverage
0,Kentucky,Adair County,1.538076,0.638028
1,Kentucky,Allen County,1.561596,0.649093
2,Kentucky,Anderson County,1.539765,0.631893
3,Kentucky,Ballard County,1.542399,0.632124
4,Kentucky,Barren County,1.544258,0.644149
...,...,...,...,...
115,Kentucky,Wayne County,1.510356,0.644916
116,Kentucky,Webster County,1.548963,0.648538
117,Kentucky,Whitley County,1.574161,0.677980
118,Kentucky,Wolfe County,1.549042,0.633357
119,Kentucky,Woodford County,1.542578,0.615787